// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Generate Deep Agents Code config.toml from NemoClaw build-arg env vars.
//
// SECURITY: this file writes only non-secret provider/model metadata. Real
// provider credentials stay outside ~/.deepagents files.

import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

export type Settings = {
  model: string;
  baseUrl: string;
  providerKey: string;
  upstreamProvider: string;
  inferenceApi: string;
};

function readSettings(env: NodeJS.ProcessEnv): Settings {
  const providerKey = normalizeCommentMetadata(
    env.NEMOCLAW_PROVIDER_KEY || "inference",
    "NEMOCLAW_PROVIDER_KEY",
  );
  return {
    model: readRequiredEnv(env, "NEMOCLAW_MODEL"),
    baseUrl: normalizeInferenceBaseUrl(
      env.NEMOCLAW_INFERENCE_BASE_URL || "https://inference.local/v1",
    ),
    providerKey,
    upstreamProvider: normalizeCommentMetadata(
      env.NEMOCLAW_UPSTREAM_PROVIDER || env.NEMOCLAW_PROVIDER_KEY || "inference",
      "NEMOCLAW_UPSTREAM_PROVIDER",
    ),
    inferenceApi: normalizeCommentMetadata(
      env.NEMOCLAW_INFERENCE_API || "openai-completions",
      "NEMOCLAW_INFERENCE_API",
    ),
  };
}

function readRequiredEnv(env: NodeJS.ProcessEnv, name: string): string {
  const value = env[name];
  if (!value) throw new Error(`${name} is required`);
  return value;
}

function normalizeCommentMetadata(value: string, name: string): string {
  if (/[\p{Cc}\p{Cf}]/u.test(value)) {
    throw new Error(`${name} must not contain control characters.`);
  }
  return value.trim();
}

function normalizeInferenceBaseUrl(value: string): string {
  if (/[\r\n]/.test(value)) {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must not contain line breaks.");
  }
  const text = value.trim();
  let url: URL;
  try {
    url = new URL(text);
  } catch {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must be a valid URL.");
  }

  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must use HTTP or HTTPS.");
  }
  if (url.username || url.password) {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must not include credentials.");
  }
  if (url.search || url.hash) {
    throw new Error("NEMOCLAW_INFERENCE_BASE_URL must not include query strings or fragments.");
  }

  return text;
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

/**
 * Return the model identifier NemoClaw should write into the deepagents
 * config.toml as the value NemoClaw prepends `openai:` to.
 *
 * Two contradictory shapes reach `NEMOCLAW_MODEL` at build time:
 *   1. A bare model id — this is what NemoClaw sets non-interactively via
 *      `src/lib/onboard/providers.ts::getNonInteractiveModel`. The bare id
 *      may legally contain `:` — the `NEMOCLAW_MODEL` build-arg validator's
 *      regex explicitly allows `:`, precisely because Ollama tags carry a
 *      `<name>:<tag>` separator (e.g. `qwen2.5:7b`, `llama3.1:8b-instruct-q4_0`).
 *   2. An `openai:<model>` provider-qualified id — some callers pre-prefix
 *      the identifier with the deepagents provider label; without a strip
 *      the emitted default would become `openai:openai:<model>` (a double
 *      prefix that the deepagents CLI rejects). See the existing regression
 *      test `test/langchain-deepagents-code-config.test.ts::does not
 *      double-prefix provider-qualified model names`.
 *
 * The previous implementation split on the FIRST `:` and returned the
 * suffix, which handled (2) but silently ate the leading segment of any
 * (1) that carried a colon — producing `openai:7b` in place of
 * `openai:qwen2.5:7b` (#6325).
 *
 * Strip ONLY the exact `openai:` provider label — the sole provider we
 * emit under `[models.providers.openai]`. Any other colon in the model id
 * is part of the model tag itself (Ollama's `name:tag` separator, HF-style
 * `org/name:tag` variant qualifiers, etc.) and MUST pass through.
 */
export function modelNameForOpenAiProvider(model: string): string {
  const trimmed = model.trim();
  const PROVIDER_PREFIX = "openai:";
  return trimmed.startsWith(PROVIDER_PREFIX) ? trimmed.slice(PROVIDER_PREFIX.length) : trimmed;
}

export function buildConfig(settings: Settings): string {
  const model = modelNameForOpenAiProvider(settings.model);
  const defaultModel = `openai:${model}`;
  return [
    "# Generated by NemoClaw. This file contains no provider secrets.",
    `# NemoClaw provider route: ${settings.providerKey}; upstream provider: ${settings.upstreamProvider}; API: ${settings.inferenceApi}.`,
    "",
    "[models]",
    `default = ${tomlString(defaultModel)}`,
    "",
    "[models.providers.openai]",
    `models = ${tomlArray([model])}`,
    'api_key_env = "DEEPAGENTS_CODE_OPENAI_API_KEY"',
    `base_url = ${tomlString(settings.baseUrl)}`,
    "enabled = true",
    "",
    "[models.providers.openai.params]",
    "# NemoClaw-managed inference.local currently exposes Chat Completions.",
    "# Remove this override when that route supports OpenAI Responses API.",
    "use_responses_api = false",
    "",
    "[update]",
    "check = false",
    "auto_update = false",
    "",
  ].join("\n");
}

export function main(): void {
  const settings = readSettings(process.env);
  const configDir = join(homedir(), ".deepagents");
  mkdirSync(join(configDir, ".state"), { recursive: true, mode: 0o770 });
  mkdirSync(join(configDir, "skills"), { recursive: true, mode: 0o770 });

  const configPath = join(configDir, "config.toml");
  writeFileSync(configPath, buildConfig(settings));
  chmodSync(configPath, 0o600);

  console.log(
    `[config] Wrote ${configPath} (model=openai:${modelNameForOpenAiProvider(settings.model)}, base_url=${settings.baseUrl})`,
  );
}

function isMainModule(): boolean {
  return process.argv[1] ? import.meta.url === pathToFileURL(resolve(process.argv[1])).href : false;
}

if (isMainModule()) main();
