// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { describe, expect, it } from "vitest";

import {
  loadAgent,
  type StateFileKeyAllowlistRestoreOwnership,
  type StateFileRestoreOwnership,
} from "./defs";

function assertKeyAllowlistOwnership(
  ownership: StateFileRestoreOwnership | undefined,
): asserts ownership is StateFileKeyAllowlistRestoreOwnership {
  ownership?.merge === "key-allowlist" ||
    (() => {
      throw new Error("Deep Agents config must declare key-allowlist restore ownership");
    })();
}

describe("agent manifest state-file restore ownership (#6334)", () => {
  it("declares selective OpenClaw config restoration", () => {
    expect(loadAgent("openclaw").stateFiles).toEqual([
      { path: "openclaw.json", strategy: "copy", restore: { merge: "openclaw-config" } },
    ]);
  });

  it("limits Deep Agents restoration to explicit user-owned preferences", () => {
    const stateFiles = loadAgent("langchain-deepagents-code").stateFiles;
    expect(stateFiles).toEqual([
      {
        path: "config.toml",
        strategy: "copy",
        restore: {
          merge: "key-allowlist",
          userKeys: [
            { key: "ui.show_scrollbar", type: "boolean" },
            { key: "ui.show_url_open_toast", type: "boolean" },
            { key: "threads.relative_time", type: "boolean" },
            { key: "threads.sort_order", type: "enum", values: ["updated_at", "created_at"] },
          ],
          requireFreshTables: ["models", "update"],
          requireFreshHeaders: [
            {
              match: "exact",
              value: "# Generated by NemoClaw. This file contains no provider secrets.",
            },
            { match: "prefix", value: "# NemoClaw provider route: " },
          ],
        },
      },
    ]);

    const configOwnership = stateFiles[0]?.restore;
    assertKeyAllowlistOwnership(configOwnership);
    const userOwnedKeys = configOwnership.userKeys.map((entry) => entry.key);
    expect(userOwnedKeys).toEqual([
      "ui.show_scrollbar",
      "ui.show_url_open_toast",
      "threads.relative_time",
      "threads.sort_order",
    ]);
    expect(configOwnership.requireFreshTables).toEqual(["models", "update"]);
    for (const runtimeOrUnknownKey of ["ui.theme", "agents", "servers"]) {
      expect(userOwnedKeys).not.toContain(runtimeOrUnknownKey);
    }
  });
});
