// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import fs from "node:fs";
import path from "node:path";

import type { SyntheticCatalog } from "./catalog";

const SAFE_FIXTURE_DIR = /^[A-Za-z0-9][A-Za-z0-9._-]*$/u;

export interface OpenClawFixtureOptions {
  outputDir: string;
  catalog: SyntheticCatalog;
  sandboxBase: string;
}

export interface OpenClawFixtureResult {
  directory: string;
  files: readonly string[];
}

function writeNewFile(directory: string, name: string, content: string): void {
  const destination = path.join(directory, name);
  if (path.dirname(destination) !== directory)
    throw new Error("fixture file escaped output directory");
  fs.writeFileSync(destination, content, { encoding: "utf8", flag: "wx", mode: 0o600 });
}

function pluginSource(): string {
  return `// Generated by the NemoClaw progressive tool-disclosure benchmark.\n\
import { createHash } from "node:crypto";\n\
import fs from "node:fs";\n\
\n\
const catalog = JSON.parse(fs.readFileSync(new URL("./catalog.json", import.meta.url), "utf8"));\n\
const callsPath = process.env.NEMOCLAW_BENCH_CALLS_PATH || "/sandbox/.nemoclaw-benchmark/calls.jsonl";\n\
\n\
function canonical(value) {\n\
  if (Array.isArray(value)) return "[" + value.map(canonical).join(",") + "]";\n\
  if (value && typeof value === "object") {\n\
    return "{" + Object.keys(value).sort().map((key) => JSON.stringify(key) + ":" + canonical(value[key])).join(",") + "}";\n\
  }\n\
  return JSON.stringify(value);\n\
}\n\
\n\
function sha256(value) {\n\
  return createHash("sha256").update(value, "utf8").digest("hex");\n\
}\n\
\n\
function execute(tool, args) {\n\
  const argumentsSha256 = sha256(canonical(args));\n\
  const nonce = "nonce_" + sha256(tool.handler.key + "\\0" + canonical(args)).slice(0, 20);\n\
  const result = {\n\
    ok: true,\n\
    tool_name: tool.definition.function.name,\n\
    category: tool.category,\n\
    operation: tool.operation,\n\
    nonce,\n\
    arguments_sha256: argumentsSha256,\n\
    summary: tool.operation.replaceAll("_", " ") + " completed for " + String(args.resource_id),\n\
  };\n\
  fs.appendFileSync(callsPath, JSON.stringify({\n\
    tool_name: result.tool_name,\n\
    arguments_sha256: argumentsSha256,\n\
    result_nonce: nonce,\n\
    success: true,\n\
  }) + "\\n", { encoding: "utf8", mode: 0o660 });\n\
  return result;\n\
}\n\
\n\
export default function registerBenchmarkTools(api) {\n\
  if (api.registrationMode && api.registrationMode !== "full") return;\n\
  for (const tool of catalog.tools) {\n\
    const definition = tool.definition.function;\n\
    api.registerTool({\n\
      name: definition.name,\n\
      label: definition.name,\n\
      description: definition.description,\n\
      parameters: definition.parameters,\n\
      async execute(_toolCallId, params) {\n\
        const result = execute(tool, params);\n\
        return {\n\
          content: [{ type: "text", text: JSON.stringify(result) }],\n\
          details: result,\n\
        };\n\
      },\n\
    });\n\
  }\n\
}\n`;
}

function dockerfile(sandboxBase: string): string {
  return `ARG SANDBOX_BASE=${sandboxBase}\n\
FROM \${SANDBOX_BASE}\n\
\n\
ARG NEMOCLAW_TOOL_DISCLOSURE=progressive\n\
ENV NEMOCLAW_TOOL_DISCLOSURE=\${NEMOCLAW_TOOL_DISCLOSURE}\n\
\n\
COPY plugin/ /opt/nemoclaw-tool-disclosure-benchmark/\n\
RUN mkdir -p /sandbox/.openclaw/extensions \\\n && cp -a /opt/nemoclaw-tool-disclosure-benchmark /sandbox/.openclaw/extensions/nemoclaw-tool-disclosure-benchmark \\\n && install -d -m 2770 -o sandbox -g sandbox /sandbox/.nemoclaw-benchmark \\\n && openclaw doctor --fix\n\
\n\
WORKDIR /opt/nemoclaw\n`;
}

/** Generate a self-contained custom-image context for an OpenClaw catalog size. */
export function writeOpenClawFixture(options: OpenClawFixtureOptions): OpenClawFixtureResult {
  const root = path.resolve(options.outputDir);
  if (fs.existsSync(root)) {
    const stat = fs.lstatSync(root);
    if (stat.isSymbolicLink() || !stat.isDirectory()) {
      throw new Error("OpenClaw fixture output must be a real directory");
    }
    if (fs.readdirSync(root).length > 0) throw new Error("OpenClaw fixture output must be empty");
  } else {
    fs.mkdirSync(root, { recursive: true, mode: 0o700 });
  }
  if (!SAFE_FIXTURE_DIR.test(path.basename(root))) {
    throw new Error("OpenClaw fixture directory has an unsafe name");
  }

  const pluginDir = path.join(root, "plugin");
  fs.mkdirSync(pluginDir, { mode: 0o700 });
  const names = options.catalog.tools.map((tool) => tool.definition.function.name);
  writeNewFile(pluginDir, "catalog.json", `${JSON.stringify(options.catalog, null, 2)}\n`);
  writeNewFile(pluginDir, "index.js", pluginSource());
  writeNewFile(
    pluginDir,
    "package.json",
    `${JSON.stringify(
      {
        name: "nemoclaw-tool-disclosure-benchmark",
        version: "1.0.0",
        private: true,
        type: "module",
        openclaw: { extensions: ["./index.js"] },
      },
      null,
      2,
    )}\n`,
  );
  writeNewFile(
    pluginDir,
    "openclaw.plugin.json",
    `${JSON.stringify(
      {
        id: "nemoclaw-tool-disclosure-benchmark",
        name: "NemoClaw Tool Disclosure Benchmark",
        version: "1.0.0",
        description: "Deterministic synthetic tools for progressive disclosure benchmarks.",
        contracts: { tools: names },
        configSchema: { type: "object", properties: {}, additionalProperties: false },
      },
      null,
      2,
    )}\n`,
  );
  writeNewFile(root, "Dockerfile", dockerfile(options.sandboxBase));
  writeNewFile(root, ".dockerignore", "*\n!Dockerfile\n!plugin\n!plugin/**\n");

  return {
    directory: root,
    files: [
      ".dockerignore",
      "Dockerfile",
      "plugin/catalog.json",
      "plugin/index.js",
      "plugin/openclaw.plugin.json",
      "plugin/package.json",
    ],
  };
}
