// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { buildConservativeClaims } from "./statistics";
import {
  type ConfidenceInterval,
  type EvidenceArtifact,
  TOOL_DISCLOSURE_PERFORMANCE_TEST_SCHEMA_VERSION,
  type ToolDisclosureManifest,
  type ToolDisclosureSummary,
} from "./types";
import { validatePublicManifestFields } from "./validation";

export { buildConservativeClaims } from "./statistics";

export interface MarkdownReportOptions {
  artifacts?: readonly EvidenceArtifact[];
}

/** Render a public report using only schema fields that cannot contain task content. */
export function renderToolDisclosureMarkdown(
  manifest: ToolDisclosureManifest,
  summary: ToolDisclosureSummary,
  options: MarkdownReportOptions = {},
): string {
  validateInputs(manifest, summary, options.artifacts ?? []);
  const claims = buildConservativeClaims(summary);
  if (JSON.stringify(claims) !== JSON.stringify(summary.claims)) {
    throw new Error("summary claims are stale or were not generated by the claim gate");
  }

  const lines: string[] = [
    "# Progressive Tool-Disclosure Performance Test",
    "",
    `Schema: \`${TOOL_DISCLOSURE_PERFORMANCE_TEST_SCHEMA_VERSION}\`  `,
    `Performance Test: \`${safeInline(manifest.performance_test_id)}\`  `,
    `Generated: ${safeInline(summary.generated_at)}  `,
    `SUT: \`${safeInline(manifest.sut.git_ref)}\` at \`${safeInline(manifest.sut.git_sha)}\`  `,
    `Harness: \`${safeInline(manifest.harness.git_ref)}\` at \`${safeInline(
      manifest.harness.git_sha,
    )}\``,
    "",
    "## Validated claims",
    "",
  ];

  if (claims.length === 0) {
    lines.push(
      "No cross-agent improvement claim cleared all two-campaign gates. See the measured results and gate table below.",
    );
  } else {
    for (const claim of claims) lines.push(`- ${claim}`);
  }

  lines.push(
    "",
    "These claims cover a deterministic synthetic tool catalog and the recorded system, model, hardware, and task corpus only. Progressive disclosure is a context optimization, not an authorization boundary. The OpenClaw native-catalog results do not establish compaction of mcporter-managed MCP tools.",
    "",
    "## Test environment",
    "",
    "| Field | Recorded value |",
    "| --- | --- |",
    `| Accelerator | ${cell(
      manifest.environment.accelerator_count === 0
        ? "none"
        : `${manifest.environment.accelerator_count} × ${manifest.environment.accelerator_type}: ${manifest.environment.accelerator_model}`,
    )} |`,
    `| Accelerator architecture | ${cell(manifest.environment.accelerator_architecture)} |`,
    `| Accelerator driver / runtime | ${cell(
      `${manifest.environment.accelerator_driver_version} / ${manifest.environment.accelerator_runtime}`,
    )} |`,
    `| CPU / RAM | ${cell(
      `${manifest.environment.cpu_count} × ${manifest.environment.cpu_model}; ${formatNumber(
        manifest.environment.ram_gib,
      )} GiB`,
    )} |`,
    `| OS / architecture | ${cell(
      `${manifest.environment.operating_system} / ${manifest.environment.architecture}`,
    )} |`,
    `| Model | ${cell(`${manifest.inference.model_id} @ ${manifest.inference.model_revision}`)} |`,
    `| vLLM image | ${cell(
      `${manifest.inference.container_image} @ ${manifest.inference.container_digest}`,
    )} |`,
    `| vLLM version | ${cell(manifest.inference.vllm_version)} |`,
    `| Tool / reasoning parser | ${cell(
      `${manifest.inference.tool_call_parser} / ${manifest.inference.reasoning_parser}`,
    )} |`,
    `| Public vLLM flags | ${cell(manifest.inference.public_vllm_flags.join(" ") || "(none)")} |`,
    `| OpenShell | ${cell(manifest.environment.openshell_version)} |`,
    `| Agent versions | ${cell(
      manifest.protocol.agents
        .map((agent) => `${agent}=${manifest.environment.agent_versions[agent]}`)
        .join(", "),
    )} |`,
    `| Power / performance state | ${cell(manifest.environment.power_state)} |`,
    "",
    "## Exact initial schema visibility",
    "",
    "| Campaign | Agent | Catalog tools | Direct tokens | Progressive tokens | Reduction | Direct tools | Progressive tools |",
    "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
  );

  for (const visibility of summary.static_visibility) {
    lines.push(
      `| ${cell(visibility.campaign_id)} | ${cell(visibility.agent)} | ${visibility.catalog_size} | ` +
        `${visibility.direct.tokenizer_tokens} | ${visibility.progressive.tokenizer_tokens} | ` +
        `${formatPercent(visibility.reduction.tokenizer_tokens_percent)} | ` +
        `${visibility.direct.tool_count} | ${visibility.progressive.tool_count} |`,
    );
  }
  if (summary.static_visibility.length === 0)
    lines.push("| (no measurements) | — | — | — | — | — | — | — |");

  lines.push(
    "",
    "Token counts above are exact captures. If a cell has repeated captures, the summary rejects it when byte, token, or tool counts differ.",
    "",
    "## Paired task results",
    "",
    "All differences are progressive minus direct. Negative token and latency values favor progressive disclosure; positive success values favor progressive disclosure.",
    "",
    "| Campaign | Phase | Agent | Catalog | Paired tasks | Success Δ pp (95% CI) | Initial schema token Δ (95% CI) | Total prompt token Δ (95% CI) | First response byte Δ ms (95% CI) | E2E latency Δ ms (95% CI) |",
    "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
  );
  for (const result of summary.comparison_cells) {
    const success = result.differences.success_percentage_points;
    lines.push(
      `| ${cell(result.campaign_id)} | ${cell(result.phase)} | ${cell(result.agent)} | ` +
        `${result.catalog_size} | ${success.paired_tasks} | ${formatInterval(success)} | ` +
        `${formatInterval(result.differences.initial_tool_schema_tokens)} | ` +
        `${formatOptionalInterval(result.differences.total_prompt_tokens)} | ` +
        `${formatOptionalInterval(result.differences.time_to_first_response_byte_ms)} | ` +
        `${formatOptionalInterval(result.differences.end_to_end_time_ms)} |`,
    );
  }
  if (summary.comparison_cells.length === 0) {
    lines.push("| (no measurements) | — | — | — | — | — | — | — | — | — |");
  }

  const gates = summary.claim_gates;
  lines.push(
    "",
    "## Public claim gates",
    "",
    `Success noninferiority requires the paired 95% CI lower bound to be at least ${formatNumber(
      gates.noninferiority_margin_percentage_points,
    )} percentage points. Improvement claims require a paired 95% CI wholly below zero in each of exactly two campaigns for every named agent.`,
    "",
    "| Campaign | Agent | Success noninferior | Initial schema tokens improved | E2E latency improved | Reasons when blocked |",
    "| --- | --- | --- | --- | --- | --- |",
  );
  for (const gate of gates.campaign_agent_gates) {
    lines.push(
      `| ${cell(gate.campaign_id)} | ${cell(gate.agent)} | ${passFail(
        gate.success_noninferior,
      )} | ${passFail(gate.initial_schema_tokens_improved)} | ${passFail(
        gate.end_to_end_latency_improved,
      )} | ${cell(gate.reasons.join("; ") || "—")} |`,
    );
  }
  lines.push(
    "",
    `- Cross-agent success noninferiority: ${passFail(gates.cross_agent_success_noninferior)}`,
    `- Cross-agent initial serialized tool-schema token improvement: ${passFail(
      gates.cross_agent_initial_schema_tokens_improved,
    )}`,
    `- Cross-agent end-to-end latency improvement: ${passFail(
      gates.cross_agent_end_to_end_latency_improved,
    )}`,
    "",
    "## Method",
    "",
    `Task-level progressive/direct pairs were resampled with a deterministic paired bootstrap (${summary.bootstrap_samples.toLocaleString(
      "en-US",
    )} samples, seed ${summary.bootstrap_seed}). Repetitions were first averaged within each task, so tasks—not individual attempts—are the statistical unit. Setup failures are excluded; timeouts, incorrect calls, model errors, and context overflows are scored failures.`,
    "",
    "First-response-byte timing is reported only for streaming inference requests. It is transport TTFB, not a claim about the first decoded content token.",
    "",
    "The static catalog is synthetic. Exact tool names, arguments, nonces, prompts, response bodies, endpoint URLs, credentials, hostnames, usernames, and local paths are not included in this report or its numeric summary.",
  );

  const artifacts = options.artifacts ?? [];
  if (artifacts.length > 0) {
    lines.push(
      "",
      "## Evidence artifacts",
      "",
      "| Artifact | Kind | Bytes | SHA-256 |",
      "| --- | --- | ---: | --- |",
    );
    for (const artifact of artifacts) {
      lines.push(
        `| ${cell(artifact.file_name)} | ${cell(artifact.kind)} | ${artifact.byte_length} | \`${artifact.sha256}\` |`,
      );
    }
  }

  return `${lines.join("\n")}\n`;
}

function validateInputs(
  manifest: ToolDisclosureManifest,
  summary: ToolDisclosureSummary,
  artifacts: readonly EvidenceArtifact[],
): void {
  validatePublicManifestFields(manifest);
  if (
    manifest.schema_version !== TOOL_DISCLOSURE_PERFORMANCE_TEST_SCHEMA_VERSION ||
    summary.schema_version !== TOOL_DISCLOSURE_PERFORMANCE_TEST_SCHEMA_VERSION
  ) {
    throw new Error("manifest and summary must use the tool-disclosure performance test schema");
  }
  if (manifest.performance_test_id !== summary.performance_test_id) {
    throw new Error("manifest and summary performance test IDs do not match");
  }
  for (const artifact of artifacts) {
    if (artifact.file_name.includes("/") || artifact.file_name.includes("\\")) {
      throw new Error(`artifact ${artifact.artifact_id} must use a leaf file name`);
    }
    if (!/^[a-f0-9]{64}$/.test(artifact.sha256)) {
      throw new Error(`artifact ${artifact.artifact_id} has an invalid SHA-256`);
    }
  }
}

function formatInterval(interval: ConfidenceInterval): string {
  return `${formatNumber(interval.estimate)} [${formatNumber(interval.lower_95)}, ${formatNumber(
    interval.upper_95,
  )}]`;
}

function formatOptionalInterval(interval: ConfidenceInterval | undefined): string {
  return interval ? formatInterval(interval) : "—";
}

function formatPercent(value: number): string {
  return `${formatNumber(value)}%`;
}

function formatNumber(value: number): string {
  if (Number.isInteger(value)) return String(value);
  return value.toFixed(3).replace(/0+$/, "").replace(/\.$/, "");
}

function passFail(value: boolean): string {
  return value ? "PASS" : "BLOCKED";
}

function safeInline(value: string): string {
  return value
    .replace(/[\r\n`]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function cell(value: string): string {
  return safeInline(value).replaceAll("|", "\\|") || "—";
}
